services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ccisj-backend
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    command: ./node_modules/.bin/tsx watch src/server.ts
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: ccisj-frontend
    ports:
      - '5173:5173'
    volumes:
      - ../frontend/src:/app/src
    command: ./node_modules/.bin/vite --host 0.0.0.0
    depends_on:
      - backend
    restart: unless-stopped
